# Generated by Django 5.2.6 on 2025-10-03 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('d', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveIntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closets', to='user.catalog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview', models.ImageField(upload_to='project_preview/')),
                ('teg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tegproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orient', models.IntegerField()),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveIntegerField()),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='user.catalog')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='user.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField()),
                ('crew_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cosmonauts', models.ManyToManyField(related_name='missions', to='user.cosmonauts')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='InnerComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orient', models.IntegerField()),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('d', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveIntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_components', to='user.catalog')),
                ('closets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_components', to='project.closet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_components', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orient', models.IntegerField()),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('d', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveIntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_systems', to='user.catalog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_systems', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orient', models.IntegerField()),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('d', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveIntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='user.catalog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('d', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveIntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='user.catalog')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='project.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='closet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closets', to='project.project'),
        ),
        migrations.CreateModel(
            name='SettingsSpaceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recursive_water', models.PositiveIntegerField(default=95)),
                ('max_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ValueResourceCloset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='project.closet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_closets', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_closets', to='user.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueResourceCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='project.compartment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_compartments', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_compartments', to='user.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueResourceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('cosmonaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='project.component')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_components', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_components', to='user.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueResourceCosmonauts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('cosmonaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='user.cosmonauts')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_cosmonauts', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_cosmonauts', to='user.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueResourceExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='project.externalsystems')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_external_systems', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_external_systems', to='user.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueResourceInnerComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('inner_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='project.innercomponent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_inner_components', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_inner_components', to='user.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueResourceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='project.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_modules', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_modules', to='user.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('d', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveIntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='user.catalog')),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='project.compartment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueResourceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(verbose_name=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources_zones', to='project.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_resources_zones', to='user.resource')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_resources', to='project.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='component',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='project.zone'),
        ),
        migrations.AddField(
            model_name='closet',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closets', to='project.zone'),
        ),
    ]
