# Generated by Django 5.2.6 on 2025-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsspacestation',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
