# Generated by Django 5.2.6 on 2025-10-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_settingsspacestation_max_price'),
        ('user', '0003_alter_teg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tegproject'),
        ),
    ]
