# Generated by Django 5.2.6 on 2025-10-03 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ES', 'external-systems'), ('CO', 'components'), ('SL', 'closets'), ('ZN', 'zones'), ('CM', 'compartments'), ('MO', 'modules')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='catalog_photo/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmonauts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='cosmonauts_avatar/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmonauts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultValueCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.PositiveIntegerField(blank=True, null=True)),
                ('h', models.PositiveIntegerField(blank=True, null=True)),
                ('d', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_value', to='user.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='material_photo/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='res_icons/')),
                ('limit', models.IntegerField()),
                ('is_limit_type_big', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('is_stock_percentage', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultResourceCosmonauts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(default=False)),
                ('cosmonaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_resources', to='user.cosmonauts')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_resources_catalogs', to='user.resource')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultResourceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_disposable', models.BooleanField(default=False)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_resources', to='user.catalog')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_resources_cosmonauts', to='user.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tegs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='teg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teg'),
        ),
        migrations.CreateModel(
            name='TegProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teg_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
