# Generated by Django 5.2.6 on 2025-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='measurement',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
